

INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('China', 'China', 'China@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('India', 'India', 'India@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('USA', 'USA', 'USA@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Indonesi',' Indonesia', 'Indonesia@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Brazil',' Brazil', 'Brazil@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Pakistan', 'Pakistan', 'Pakistan@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Nigeria',' igeria', 'Nigeria@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Bangladesh',' Bangladesh',' Bangladesh@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Russia',' Russia', 'Russia@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Japan', 'Japan', 'Japan@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Mexico',' Mexico', 'Mexico@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Philippi',' Philippines', 'Philippines@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Ethiopia', 'Ethiopia', 'Ethiopia@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Vietnam', 'ietnam', 'Vietnam@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Egypt', 'Egypt', 'Egypt@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Germany', 'ermany',' Germany@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('the',' Coth', 'the@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Iran', 'ran', 'Iran@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Turkey',' Turkey', 'Turkey@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Thailand', 'Thailand', 'Thailand@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('France',' France', 'France@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('United K','iUnited', 'United@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('South Af','South', 'South@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Myanmar', 'yanmar', 'Myanmar@yahoo');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('South Ko','South', 'South@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Colombia', 'Colombia', 'Colombia@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Kenya', 'Kenya', 'Kenya@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Spain', 'Spain', 'Spain@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Argentina',' Argentina', 'Argentina@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Ukraine', 'kraine', 'Ukraine@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Sudan', 'Sudan', 'Sudan@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Algeria','lgeria', 'Algeria@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Poland',' Poland', 'Poland@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Canada',' Canada', 'Canada@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Morocco', 'orocco', 'Morocco@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Saudi Ar','Saudi', 'Saudi@yahoo.com' );
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Uzbekistan',' Uzbekistan', 'Uzbekistan@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Peru', 'Peru', 'Peru@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Angola',' Angola', 'Angola@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Malaysia', 'Malaysia', 'Malaysia@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Mozambique',' Mozambique',' Mozambique@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Ghana', 'Ghana', 'Ghana@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Yemen', 'Yemen', 'Yemen@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Nepal', 'Nepal', 'Nepal@yahoo.com');
INSERT INTO TBL_EMPLOYEES( first_name, last_name, email) VALUES('Venezuela',' Venezuela', 'Venezuela@yahoo.com');